### ISSUE TITLE
Play integration doesn't support HTTP (only HTTPS)

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-grpc#386]
I'm trying to run a simple grpc service in Play and have followed the instructions at https://developer.lightbend.com/docs/akka-grpc/current/play-framework.html including enabling HTTP/2 and HTTPS support.

When I hit any grpc endpoint over HTTPS using `grpcurl` I get the following exception in Play:

```
[error] a.a.RepointableActorRef - Error during preStart in [MapAsyncUnordered(0,akka.http.impl.engine.http2.Http2Blueprint$$$Lambda$5177/1682816817@229df8c8)]: size must be positive
java.lang.IllegalArgumentException: size must be positive
    at akka.stream.impl.FixedSizeBuffer$.apply(Buffers.scala:64)
    at akka.stream.impl.Buffer$.apply(Buffers.scala:45)
    at akka.stream.impl.Buffer$.apply(Buffers.scala:40)
    at akka.stream.impl.fusing.MapAsyncUnordered$$anon$26.preStart(Ops.scala:1277)
    at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
    at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
    at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
    at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
    at akka.actor.Actor.aroundPreStart(Actor.scala:528)
    at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
```
If I hit it over HTTP (`--plaintext` arg to grpcurl) I get `[warn] a.a.ActorSystemImpl - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: PRI`.

I'm running the Play server in dev mode for the above. I'd hoped to compare to what happens in prod mode, but after running `sbt dist` and unzipping the result and starting it, I get the following:

```
Oops, cannot start the server.
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: play/api/mvc/akkahttp/AkkaHttpHandler
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
    at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
    at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
    at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:138)
    at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:536)
    at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:160)
    at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:123)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
    at com.google.inject.Guice.createInjector(Guice.java:99)
    at com.google.inject.Guice.createInjector(Guice.java:84)
    at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
    at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
    at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
    at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
    at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
    at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.NoClassDefFoundError: play/api/mvc/akkahttp/AkkaHttpHandler
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getDeclaredConstructors(Class.java:2020)
    at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
    at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:100)
    at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:661)
    at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:885)
    at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:808)
    at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:285)
    at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:217)
    at com.google.inject.internal.InjectorImpl.createParameterInjector(InjectorImpl.java:965)
    at com.google.inject.internal.InjectorImpl.getParametersInjectors(InjectorImpl.java:953)
    at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:71)
    at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
    at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
    at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
    at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
    ... 20 more
Caused by: java.lang.ClassNotFoundException: play.api.mvc.akkahttp.AkkaHttpHandler
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 41 more
```

I'm using Scala 2.12.2, Play 2.6.18, and Akka gRPC 0.2.

Any pointers for what might be wrong in my setup? Is there a functional grpc Play app I could compare to?

**Comment by raboof** [comment]
The `java.lang.IllegalArgumentException: size must be positive` I'm afraid is a problem in Akka HTTP 10.1.4. Updating to 10.1.5 should fix this problem. When we release Akka gRPC 0.3 it will obviously also depend on at least 10.1.5.

`java.lang.ClassNotFoundException: play.api.mvc.akkahttp.AkkaHttpHandler` suggests you might have the Netty backend loaded instead of the Akka HTTP one. Akka gRPC only works with the Akka HTTP backend.

Let us know if this helps!

**Comment by ctoomey** [comment]
I upgraded to Akka HTTP 10.1.5 and that indeed resolved the IllegalArgumentException.

But I'm still getting the `java.lang.ClassNotFoundException: play.api.mvc.akkahttp.AkkaHttpHandler` error, and am sure I am running the Akka HTTP backend. And that class is not included in any of the jars pulled in by the GRPC or HTTP2 support sbt plugins; the list of typesafe packages is below. Looks like  there's a missing package dependency, what package provides that class?

sbt: com.typesafe.akka:akka-actor_2.12:2.5.14:jar
sbt: com.typesafe.akka:akka-http2-support_2.12:10.1.5:jar
sbt: com.typesafe.akka:akka-http-core_2.12:10.1.5:jar
sbt: com.typesafe.akka:akka-http_2.12:10.1.5:jar
sbt: com.typesafe.akka:akka-parsing_2.12:10.1.5:jar
sbt: com.typesafe.akka:akka-protobuf_2.12:2.5.14:jar
sbt: com.typesafe.akka:akka-slf4j_2.12:2.5.11:jar
sbt: com.typesafe.akka:akka-stream_2.12:2.5.14:jar
sbt: com.typesafe.play:build-link:2.6.18:jar
sbt: com.typesafe.play:cachecontrol_2.12:1.1.3:jar
sbt: com.typesafe.play:filters-helpers_2.12:2.6.18:jar
sbt: com.typesafe.play:play-ahc-ws-standalone_2.12:1.1.10:jar
sbt: com.typesafe.play:play-ahc-ws_2.12:2.6.18:jar
sbt: com.typesafe.play:play-akka-http2-support_2.12:2.6.18:jar
sbt: com.typesafe.play:play-akka-http-server_2.12:2.6.18:jar
sbt: com.typesafe.play:play-cache_2.12:2.6.18:jar
sbt: com.typesafe.play:play-ehcache_2.12:2.6.18:jar
sbt: com.typesafe.play:play-exceptions:2.6.18:jar
sbt: com.typesafe.play:play-functional_2.12:2.6.10:jar
sbt: com.typesafe.play:play-guice_2.12:2.6.18:jar
sbt: com.typesafe.play:play-jdbc-api_2.12:2.6.18:jar
sbt: com.typesafe.play:play-jdbc_2.12:2.6.18:jar
sbt: com.typesafe.play:play-json_2.12:2.6.10:jar
sbt: com.typesafe.play:play-logback_2.12:2.6.18:jar
sbt: com.typesafe.play:play-netty-utils:2.6.18:jar
sbt: com.typesafe.play:play-server_2.12:2.6.18:jar
sbt: com.typesafe.play:play-specs2_2.12:2.6.18:jar
sbt: com.typesafe.play:play-streams_2.12:2.6.18:jar
sbt: com.typesafe.play:play-test_2.12:2.6.18:jar
sbt: com.typesafe.play:play-ws-standalone-json_2.12:1.1.10:jar
sbt: com.typesafe.play:play-ws-standalone-xml_2.12:1.1.10:jar
sbt: com.typesafe.play:play-ws-standalone_2.12:1.1.10:jar
sbt: com.typesafe.play:play-ws_2.12:2.6.18:jar
sbt: com.typesafe.play:play_2.12:2.6.18:jar
sbt: com.typesafe.play:shaded-asynchttpclient:1.1.10:jar
sbt: com.typesafe.play:shaded-oauth:1.1.10:jar
sbt: com.typesafe.play:twirl-api_2.12:1.3.15:jar

**Comment by ctoomey** [comment]
The `java.lang.ClassNotFoundException: play.api.mvc.akkahttp.AkkaHttpHandler` error went away when I switched to Play 2.7.0-M3 from 2.6.18.

But I still can't get either `grpcurl -plaintext` to the HTTP port or `grpcurl -insecure` to the HTTPS port or a Java grpc netty client built with `io.grpc.netty.NettyChannelBuilder` and `io.grpc.netty.NegotiationType.PLAINTEXT` to work (though all of these work against a Netty grpc server).

With the latter I see this log message on the server

`[warn] a.a.ActorSystemImpl - Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: PRI`

and this debug logging from the client

```
19:53:08.361 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
19:53:08.365 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
19:53:08.413 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
19:53:08.413 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
19:53:08.430 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: MacOS
19:53:08.431 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
19:53:08.431 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
19:53:08.432 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
19:53:08.433 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
19:53:08.434 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
19:53:08.434 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
19:53:08.435 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
19:53:08.435 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
19:53:08.435 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
19:53:08.435 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
19:53:08.435 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/xg/fz3p1l8j1z36_pkqf5czc8q00000gn/T (java.io.tmpdir)
19:53:08.435 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
19:53:08.437 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
19:53:08.437 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 3817865216 bytes
19:53:08.437 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
19:53:08.437 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
19:53:08.446 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
19:53:09.189 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
19:53:09.189 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
19:53:09.196 [grpc-default-executor-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
19:53:09.197 [grpc-default-executor-0] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@2aa1a976
19:53:09.244 [grpc-default-executor-0] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
19:53:09.244 [grpc-default-executor-0] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
19:53:09.279 [grpc-default-executor-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 6438 (auto-detected)
19:53:09.282 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
19:53:09.282 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
19:53:09.287 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1)
19:53:09.288 [grpc-default-executor-0] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
19:53:09.289 [grpc-default-executor-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 80:e6:50:ff:fe:0a:5f:0c (auto-detected)
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
19:53:09.310 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
19:53:09.312 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
19:53:09.312 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
19:53:09.312 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
19:53:09.312 [grpc-default-executor-0] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
19:53:09.318 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
19:53:09.318 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
19:53:09.318 [grpc-default-executor-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
19:53:09.333 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
19:53:09.333 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
19:53:09.333 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
19:53:09.333 [grpc-default-executor-0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
19:53:09.344 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x3d1a3907, L:/127.0.0.1:51906 - R:localhost/127.0.0.1:9000] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
19:53:09.370 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x3d1a3907, L:/127.0.0.1:51906 - R:localhost/127.0.0.1:9000] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
19:53:09.377 [grpc-default-worker-ELG-1-3] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xb946d64b, L:/0:0:0:0:0:0:0:1:51907 - R:localhost/0:0:0:0:0:0:0:1:9000] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
19:53:09.377 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x3d1a3907, L:/127.0.0.1:51906 - R:localhost/127.0.0.1:9000] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=1 length=77 bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
19:53:09.378 [grpc-default-worker-ELG-1-3] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xb946d64b, L:/0:0:0:0:0:0:0:1:51907 - R:localhost/0:0:0:0:0:0:0:1:9000] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
19:53:09.381 [grpc-default-worker-ELG-1-3] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xb946d64b, L:/0:0:0:0:0:0:0:1:51907 - R:localhost/0:0:0:0:0:0:0:1:9000] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=1 length=77 bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
19:53:09.382 [grpc-default-worker-ELG-1-4] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa02610e9, L:/fe80:0:0:0:0:0:0:1%1:51908 - R:localhost/fe80:0:0:0:0:0:0:1%1:9000] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
19:53:09.382 [grpc-default-worker-ELG-1-3] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0xb946d64b, L:/0:0:0:0:0:0:0:1:51907 - R:localhost/0:0:0:0:0:0:0:1:9000] Sent GOAWAY: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
19:53:09.385 [grpc-default-worker-ELG-1-2] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0x3d1a3907, L:/127.0.0.1:51906 ! R:localhost/127.0.0.1:9000] Sending GOAWAY failed: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:418)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1376)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:619)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:257)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
19:53:09.386 [grpc-default-worker-ELG-1-4] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa02610e9, L:/fe80:0:0:0:0:0:0:1%1:51908 - R:localhost/fe80:0:0:0:0:0:0:1%1:9000] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
19:53:09.392 [grpc-default-worker-ELG-1-4] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa02610e9, L:/fe80:0:0:0:0:0:0:1%1:51908 - R:localhost/fe80:0:0:0:0:0:0:1%1:9000] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=1 length=77 bytes=4669727374207265636569766564206672616d6520776173206e6f742053455454494e47532e204865782064756d7020666f7220666972737420352062797465...
19:53:09.392 [grpc-default-worker-ELG-1-4] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0xa02610e9, L:/fe80:0:0:0:0:0:0:1%1:51908 - R:localhost/fe80:0:0:0:0:0:0:1%1:9000] Sent GOAWAY: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
Disconnected from the target VM, address: '127.0.0.1:51903', transport: 'socket'
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:101)
	at hw.helloworld.HelloWorldGrpc$HelloWorldBlockingStub.sayAnything(HelloWorldGrpc.scala:75)
	at hellogrpc_demo.HelloWorldClient$.main(HelloWorldClient.scala:61)
	at hellogrpc_demo.HelloWorldClient.main(HelloWorldClient.scala)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ctoomey** [comment]
More info: the above problem is specific to the Play integration. If I implement it directly in Akka grpc per [here](https://developer.lightbend.com/docs/akka-grpc/current/server/walkthrough.html) it works with both `grpcurl -plaintext` and with the Netty grpc client.

**Comment by raboof** [comment]
Ah, Akka gRPC indeed requires Play 2.7.x, we should probably be more explicit about that

**Comment by ctoomey** [comment]
Right, would be good to state that it requires 2.7.x to not get the class not found, but I still can't get it to successfully handle a request. Any ideas what the problem is? Can you point me to or send me a working example of Play integration?

**Comment by ctoomey** [comment]
For the non-SSL case, the problem was that since Akka HTTP doesn't support HTTP/2 upgrade negotiation, the HTTP server needs to be configured with `HttpConnectionContext(http2 = Always)` as it is in the example [here](https://developer.lightbend.com/docs/akka-grpc/current/server/walkthrough.html#serving-the-service-with-akka-http). I made the following patch locally and verified it works:

```
% git --no-pager diff
diff --git a/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala b/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
index 765df26e6..2158f9a8d 100644
--- a/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
+++ b/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
@@ -15,7 +15,8 @@ import akka.http.scaladsl.model.ws.UpgradeToWebSocket
 import akka.http.scaladsl.model.{ headers, _ }
 import akka.http.scaladsl.settings.{ ParserSettings, ServerSettings }
 import akka.http.scaladsl.util.FastFuture._
-import akka.http.scaladsl.{ ConnectionContext, Http }
+import akka.http.scaladsl.{ ConnectionContext, Http, HttpConnectionContext }
+import akka.http.scaladsl.UseHttp2._
 import akka.stream.Materializer
 import akka.stream.scaladsl._
 import akka.util.ByteString
@@ -157,7 +158,7 @@ class AkkaHttpServer(context: AkkaHttpServer.Context) extends Server {
     Await.result(bindingFuture, bindTimeout)
   }
 
-  private val httpServerBinding = context.config.port.map(port => createServerBinding(port, ConnectionContext.noEncryption(), secure = false))
+  private val httpServerBinding = context.config.port.map(port => createServerBinding(port, HttpConnectionContext(http2 = if (http2Enabled) Always else Never), secure = false))
 
   private val httpsServerBinding = context.config.sslPort.map { port =>
     val connectionContext = try {
```

For the SSL case it was my bad, I didn't have the ALPN agent properly set up when running the server. After fixing that, it also worked.

**Comment by raboof** [comment]
I think the Play version requirement is now clearer since play-grpc is its own project, and I'm not sure if we can do anything to improve messaging when the ALPN agent is not found (it is not needed on jdk11), so I guess we can close this issue. Feel free to reopen or open another issue if you have a specific idea for something that can be better documented or reported.
