### ISSUE TITLE
Service discovery doc 404 link

### ISSUE THREAD

**Issue by politrons** [akka/akka-grpc#435]
I'm really interested in use akka gRPC since all our stack is already Akka. Right now we use Restful with Service discovery, and in case we change to RPC we will need also SD. I've seen that you guys provide a SD mechanism, but I cannot reach the documentation here https://developer.lightbend.com/docs/akka-management/current/discovery.html

Could you please can provide a documentation and also tell me the grade of maturity of the feature?. 
Akka gRPC and SD is already production ready?

**Comment by raboof** [comment]
(related to https://github.com/akka/akka-management/issues/307)

**Comment by raboof** [comment]
The maturity of Service Discovery depends on the module you're using:
* config and kubernetes-api should be pretty reliable
* DNS is missing the fallback from UDP to TCP for big responses, this should be fixed soon via https://github.com/akka/akka/pull/25690
* I'm not sure about the AWS, Consul and Marathon modules. It's probably easier to use those compared to writing your own, but make sure to do your own testing there.

gRPC is in MVP mode: it is ready for consumption but lacking some of the more advanced features. Make sure to also do your own tests before going into production. We are very interested in feedback and participation here. If you rely on cancelled streams (which should probably be rare), it might be wise to wait for the Akka HTTP 10.1.6 release because that will include the fix for https://github.com/akka/akka-http/issues/2236.

**Comment by politrons** [comment]
Thanks we will do a POC and we will then.
I read the whole Service discovery documentation, but still not sure how works the Server part. In our current Service discovery implementation, we have a Server which is the one that receive the Manifest with the information of every service to be discovered, and is this sever, the one that is consumed in the Lookup by all service looking for a host and port using an endpoint. In your Service discovery architecture pattern how is the orchestration  between consumer and service discovery itself?
Do we need to have a dedicate server as service discovery?

**Comment by ignasi35** [comment]
> Do we need to have a dedicate server as service discovery?

Yes and no.

Akka's `ServiceDiscovery` supports different implementations. Meaning the serving end could be Kubernetes' DNS server, Consul, `etcd` or even a hardcoded implementation. If you already have a Server handling the metadata of the running processes then you implement your own `PolitronsServiceDiscovery` and inject that into the Akka code.

Akka's Service Discovery doesn't handle the registration. The registration step under which each process sends its metadata to a central registry service must be handled manually. Usually it's the orchestrator responsibility.
